version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            apt update
            apt install -y zip docker.io curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: ECR Auth
          command: |
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 450183644535.dkr.ecr.us-west-2.amazonaws.com
      - setup_remote_docker
      - run:
          name: Docker Build
          command: |
            docker build -t color .
            docker tag color 450183644535.dkr.ecr.us-west-2.amazonaws.com/color:latest
      - run:
          name: Docker Push
          command: |
            docker push 450183644535.dkr.ecr.us-west-2.amazonaws.com/color:latest
  test:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Performing testing
          command: echo "Running a dummy test"
  deployment:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Installing dependencies
          command: |
            apt update
            apt install -y zip curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - run:
          name: Deployment
          command: |
            aws eks update-kubeconfig --name nclouds-cluster --region us-west-2
            /root/bin/kubectl rollout restart deployment colorful -n alpha
workflows:
  nclouds:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deployment:
          requires:
            - hold
