# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Building
          command: pip install flask

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
