# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
jobs:
  build:
    working_directory: /app
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Dependancies
          command: |
            apt update
            apt install -y curl docker.io unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - setup_remote_docker
      - run:
          name: Building
          command: docker build .
      - run:
          name: aws
          command: aws s3 ls
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Building
          command: pip install flask
      - run:
          command: echo $AWS_SECRET_ACCESS_KEY

workflows:
  sample:
    jobs:
      - build
      - build-and-test:
          filters:
            branches:
              only:
                - develop
