version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            apt update
            apt install -y zip docker.io curl
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
      - run:
          name: ECR Auth
          command: |
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 450183644535.dkr.ecr.us-west-2.amazonaws.com
      - setup_remote_docker
      - run:
          name: Docker Build
          command: |
            docker build -t color .
            docker tag color 450183644535.dkr.ecr.us-west-2.amazonaws.com/color:latest
      - run:
          name: Docker Push
          command: |
            docker push 450183644535.dkr.ecr.us-west-2.amazonaws.com/color:latest
workflows:
  nclouds:
    jobs:
      - build
